name: Postman flow

on: [push]

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  generate:
    name: Generate, validate and sync postman collection
    environment: Postman
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout openapi spec
        uses: actions/checkout@v2
        with:
          repository: Theoklitos/openapi-spec
      - name: Setup credentials
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".env"
          FILE_DATA: "POSTMAN_API_KEY=${{ secrets.POSTMAN_API_TOKEN }}"
      - name: Generate and upload postman collection
        run: npx @apideck/portman -l openapi-spec.json --syncPostman true
      - run: ls -la