name: Postman flow

on: [push]

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  generate:
    name: Sync postman collection
    environment: Postman
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout openapi spec
        uses: actions/checkout@v2
        with:
          repository: Theoklitos/openapi-spec
      - run: ls -la
      - name: Setup credentials
        uses: DamianReeves/write-file-action
        with:
          path: .env-rcnet
          contents: "POSTMAN_API_KEY=${{ secrets.POSTMAN_API_TOKEN }}"
          write-mode: append
      - name: Generate & upload postman collection
        run: npx @apideck/portman -l openapi-spec.json -o /tmp/collection.postman.json --envFile .env-rcnet --syncPostman true
      - name: Validate collection w/ newman
        run: newman run /tmp/collection.postman.json
